### PR TITLE
Refactor code and remove dhclient bits

### PR DESCRIPTION
**Pull request by yun**
Fixes T1028, dhclient release and renew is already handled by netplug.

### CODE REVIEW

**Comment by hagbard-01** [comment]
Can you please fix the indents? We use 2 spaces. Why did you remove syslog?

**Comment by hagbard-01** [comment]
https://vyos.readthedocs.io/en/latest/contributing/index.html#python-coding-guidelines

**Comment by yun** [comment]
> https://vyos.readthedocs.io/en/latest/contributing/index.html#python-coding-guidelines

https://vyos.readthedocs.io/en/latest/contributing/index.html#formatting It says 4 spaces here, so what should I use?

I will re-add syslog, but I wonder why it was there, for debugging purposes?

**Comment by yun** [comment]
I re-added syslog and applied the VyOS configuration script structure mentioned in the guidelines

**Comment by hagbard-01** [comment]
I'm gonna close this one unmerged, as it turns out that the latest iso is working, so it can't be the script.

**Comment by yun** [comment]
> I'm gonna close this one unmerged, as it turns out that the latest iso is working, so it can't be the script.

Hi hagbard, which iso is that? please add for reference so I and maybe other people who read this PR can do tests.

**Pull request merged**
